cd ~/GitProjects

# J1 repos
git clone git@github.com:JupiterOne/callisto.git
git clone git@github.com:JupiterOne/data-model.git
git clone git@github.com:JupiterOne/dynamobd-dao.git
git clone git@github.com:JupiterOne/graph-aws.git
git clone git@github.com:JupiterOne/graph-azure.git
git clone git@github.com:JupiterOne/graph-cloudflare.git
git clone git@github.com:JupiterOne/graph-github.git
git clone git@github.com:JupiterOne/graph-google.git
git clone git@github.com:JupiterOne/graph-jira.git
git clone git@github.com:JupiterOne/graph-mimecast.git
git clone git@github.com:JupiterOne/graph-xmcyber.git
git clone git@github.com:JupiterOne/graph1l-proxy-service.git
git clone git@github.com:JupiterOne/integration-azure.git
git clone git@github.com:JupiterOne/integration-deployments.git
git clone git@github.com:JupiterOne/integration-engineering-toolbox.git
git clone git@github.com:JupiterOne/integration-github-actions.git
git clone git@github.com:JupiterOne/integration-google-cloud.git
git clone git@github.com:JupiterOne/integration-template.git
git clone git@github.com:JupiterOne/jupiter-integration-service.git
git clone git@github.com:JupiterOne/jupiter-maintenance-jobs.git
git clone git@github.com:JupiterOne/jupiter-managed-integration.git
git clone git@github.com:JupiterOne/jupiter-persister.git
git clone git@github.com:JupiterOne/jupiter-test-automation.git
git clone git@github.com:JupiterOne/jupiter-types.git
git clone git@github.com:JupiterOne/sdk.git
git clone git@github.com:JupiterOne/starbase.git
git clone git@github.com:JupiterOne/web-apps-core.git
git clone git@github.com:JupiterOne/web-assets.git
git clone git@github.com:JupiterOne/web-compliance.git
git clone git@github.com:JupiterOne/web-home.git
git clone git@github.com:JupiterOne/web-icons.git
git clone git@github.com:JupiterOne/web-insights.git
git clone git@github.com:JupiterOne/web-integrations.git
git clone git@github.com:JupiterOne/web-juno.git
git clone git@github.com:JupiterOne/web-juno-datatable.git
git clone git@github.com:JupiterOne/web-root.git
git clone git@github.com:JupiterOne/web-toolkit.git
